[package]
name = "piper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11"
regex = "1"
tokio = { version = "1.32.0", features = ["full"] }
egui = "0.22.0"
eframe = "0.22.0"